[versions]
ultimanexus-gradle-plugins = "1.0.0"

[plugins]
# Feature plugins
ultimanexus-feature-publish = { id = "dev.daymor.ultimanexus.jvm.gradle.feature.publish", version.ref = "ultimanexus-gradle-plugins" }

# Base plugins
ultimanexus-base-lifecycle = { id = "dev.daymor.ultimanexus.jvm.gradle.base.lifecycle", version.ref = "ultimanexus-gradle-plugins" }

# Check plugins (for self-quality)
ultimanexus-check-formatGradle = { id = "dev.daymor.ultimanexus.jvm.gradle.check.format-gradle", version.ref = "ultimanexus-gradle-plugins" }
